# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

main_fastcmh2 <- function(xfilenameR, yfilenameR, cfilenameR, alphaR, lmaxR, showProcessingR, saveAllPvalsR, doFDR_R, useDependenceFDR_R) {
    .Call('fastcmh_main_fastcmh2', PACKAGE = 'fastcmh', xfilenameR, yfilenameR, cfilenameR, alphaR, lmaxR, showProcessingR, saveAllPvalsR, doFDR_R, useDependenceFDR_R)
}

